In [2]:
import numpy as np

# 1. Convolution algorithm 구현하기

- image: m x m np array
- pattern: n x n np array
- stride도 감안해야 함. Padding, Dilation 등은 없음
- m < n 이거나, stride와 m,n이 정확히 맞아 떨어지지 않으면 Error 출력    

In [7]:
def conv(image,pattern,stride = 1):
    beg = 0
    end = pattern.shape[0]
    res = []
    
    m = image.shape[0]
    n = pattern.shape[0]
    
    if m < n:
        print("Error: m < n")
        return None
    
    if (m - n) % stride > 0:
        print("Incompatible patterns")
        return None
    
    for i in range(0,m-n+1,stride):
        k = []
        for j in range(0,m-n+1,stride):
            if i + end > m or j + end > m: continue
            
            k.append(np.sum(image[beg+i : end+i, beg+j:end+j] * (pattern)))
        res.append(k)

    return np.array(res)



In [ ]:
image = np.array([[1,2,3,3,3],[4,5,6,6,6],[7,8,9,9,9],[10,11,12,13,13],[10,11,12,13,13]])
pattern = np.array([[1,0,0],[0,1,0],[0,0,1]])

In [ ]:
conv(image, pattern,2)

array([[15, 18],
       [30, 35]])

## 기홍 답안

In [9]:
def conv(image, pattern, stride=1):
    # image: a 2d numpy array of floats, with size (m, m) for some integer m.
    # pattern: a 2d numpy array of floats, with size(n, n) for some integer n.
    # stride: the number of pixels shift over the input.
    # return: a 2d numpy of convoluted activation on image with pattern if valid. None otherwise.
    m = len(image)
    n = len(pattern)

    if m < n:
        print("Error: m < n")
        return None
    if (m - n) % stride != 0:
        print("Incompatible params")
        return None

    result_width = (m - n) // stride + 1
    result_height = (m - n) // stride + 1
    result_array = np.zeros((result_width, result_height))

    for start_col in range(0, result_width):
        for start_row in range(0, result_height):  
            curr_col = start_col * stride
            curr_row = start_row * stride
            curr_output = image[curr_row:curr_row + n, curr_col: curr_col + n] * pattern
            curr_sum = np.sum(curr_output)
            result_array[start_row][start_col] = curr_sum
    
    return result_array

In [10]:
# Test Cases
image = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10], [1, 2, 3, 4]])
pattern = np.array([[1, 0], [0, 1]])

image2 = np.array([[1, 2], [3, 4]])
image3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

image4 = np.array([[1,2,3,3,3],[4,5,6,6,6],[7,8,9,9,9],[10,11,12,13,13],[10,11,12,13,13]])
pattern2 = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(conv(image3, pattern, 1))
print(conv(pattern, image3, 2))
print(conv(image, pattern, 1))
print(conv(image4, pattern2, 2))

[[ 6.  8.]
 [12. 14.]]
Error: m < n
None
[[ 6.  8. 10.]
 [12. 14. 16.]
 [ 9. 11. 13.]]
[[15. 18.]
 [30. 35.]]


# 2. Tree가 주어졌을 때 가장 긴 Round Trip Length를 구하는 문제

In [ ]:
class BTNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

In [ ]:
def roundTripLongestRouteOfBT(root: BTNode):
    def helper(node):
        if node.left is None and node.right is None:
            return 0, 0            
        if node.left is None:
            roundLen, singleLen = helper(node.right)
            return max(roundLen, singleLen + 1), singleLen + 1
        if node.right is None:
            roundLen, singleLen = helper(node.left)
            return max(roundLen, singleLen + 1), singleLen + 1
        l_roundLen, l_singleLen = helper(node.left)
        r_roundLen, r_singleLen = helper(node.right)
        roundLen = max(l_roundLen, r_roundLen)
        return max(roundLen, l_singleLen + r_singleLen + 2), max(l_singleLen, r_singleLen) + 1
    
    return 2 * max(helper(root))

In [12]:
tree2 = BTNode(2)
tree3 = BTNode(3)
tree4 = BTNode(4)
tree6 = BTNode(6)
tree7 = BTNode(7)
"""
tree8 = BTNode(8)
tree9 = BTNode(9)
tree10 = BTNode(10)
tree11 = BTNode(11)
tree12 = BTNode(12)
tree13 = BTNode(13)
tree14 = BTNode(14)
"""

'\ntree8 = BTNode(8)\ntree9 = BTNode(9)\ntree10 = BTNode(10)\ntree11 = BTNode(11)\ntree12 = BTNode(12)\ntree13 = BTNode(13)\ntree14 = BTNode(14)\n'

In [13]:
tree4.left = tree2
tree4.right = tree6
tree2.right = tree3
tree6.right = tree7
"""
tree6.left = tree8
tree8.left = tree9
tree9.right = tree10
tree10.left = tree11
tree7.left = tree12
tree12.right = tree13
tree13.right = tree14
"""

'\ntree6.left = tree8\ntree8.left = tree9\ntree9.right = tree10\ntree10.left = tree11\ntree7.left = tree12\ntree12.right = tree13\ntree13.right = tree14\n'

In [14]:
roundTripLongestRouteOfBT(tree4)

8

In [15]:
tree2 = BTNode(2)
tree3 = BTNode(3)
tree6 = BTNode(6)
tree7 = BTNode(7)
tree9 = BTNode(9)
tree10 = BTNode(10)

In [16]:
tree9.right = tree6
tree6.left = tree3
tree6.right = tree7
tree3.left = tree2
tree7.left = tree10

In [17]:
roundTripLongestRouteOfBT(tree9)

8

## 기홍 답안

In [11]:
# Definition for binary tree node
class BTNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = 0
        self.left = left
        self.right = right

class DiameterTracker:
	def __init__(self):
		self.diameter = 0

def roundTripLongestRouteOfBT(root: BTNode) -> int:
    diameter_tracker = DiameterTracker()
    getLongestPath(root, diameter_tracker)
    return diameter_tracker.diameter * 2
	
def getLongestPath(node, diameter_tracker):
	if node is None:
	    return 0
	left_longest_path = getLongestPath(node.left, diameter_tracker)
	right_longest_path = getLongestPath(node.right, diameter_tracker)
	diameter_tracker.diameter = max(diameter_tracker.diameter, left_longest_path + right_longest_path)
	return max(left_longest_path, right_longest_path) + 1

In [5]:
# Test Cases
root_node = BTNode(4)
root_node.left, root_node.right = BTNode(2), BTNode(6)
root_node.left.right = BTNode(3)
root_node.right.right = BTNode(7)

root2 = BTNode(9)
root2.right = BTNode(6)
root2.right.left, root2.right.right = BTNode(3), BTNode(7)
root2.right.left.left = BTNode(2)
root2.right.right.left = BTNode(10)

print(roundTripLongestRouteOfBT(root_node))
print(roundTripLongestRouteOfBT(root2))

8
8
